// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXqXAKvtncpkjGTVTtkGxVRFwdAcxTD9M',
    appId: '1:959257585633:web:5fb125b0ae4246491e54a0',
    messagingSenderId: '959257585633',
    projectId: 'pblproject-b8b41',
    authDomain: 'pblproject-b8b41.firebaseapp.com',
    storageBucket: 'pblproject-b8b41.appspot.com',
    measurementId: 'G-LRWKVJ0R04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqdtLLna3SQdjD9F_jGKUNi4D6rR2MykU',
    appId: '1:959257585633:android:c5b64050120ffd961e54a0',
    messagingSenderId: '959257585633',
    projectId: 'pblproject-b8b41',
    storageBucket: 'pblproject-b8b41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlRjJ68fQepkojKqf_Rqu987c1fhWT3xg',
    appId: '1:959257585633:ios:5c92e9b7919da8571e54a0',
    messagingSenderId: '959257585633',
    projectId: 'pblproject-b8b41',
    storageBucket: 'pblproject-b8b41.appspot.com',
    iosBundleId: 'com.example.newp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlRjJ68fQepkojKqf_Rqu987c1fhWT3xg',
    appId: '1:959257585633:ios:22cfa9f0ef532e961e54a0',
    messagingSenderId: '959257585633',
    projectId: 'pblproject-b8b41',
    storageBucket: 'pblproject-b8b41.appspot.com',
    iosBundleId: 'com.example.newp.RunnerTests',
  );
}
